packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": "*"
      "@firebase/util": "*"
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  eslint-config-react-app@*:
    peerDependencies:
      eslint-plugin-flowtype: "*"
  material-table@*:
    dependencies:
      "@babel/runtime": "*"
  react-event-listener@*:
    dependencies:
      react: "*"
  react-frame-component@*:
    dependencies:
      prop-types: "*"
  react-redux@*:
    dependencies:
      react-dom: "*"
  react-router-config@*:
    dependencies:
      react-router: "*"
  react-table@*:
    dependencies:
      prop-types: "*"
  raw-loader@*:
    dependencies:
      webpack: "*"
  styled-components@*:
    dependencies:
      react-is: "*"
